# Generated by Django 3.1.5 on 2021-02-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210202_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('in_process', 'in_process'), ('delivered', 'delivered'), ('not_delivered', 'not_delivered')], default='in_process', max_length=50, verbose_name='Статус'),
        ),
    ]
