# Generated by Django 3.1.5 on 2021-02-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210202_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
